### ISSUE TITLE
New version on Hackage?

### ISSUE THREAD

**Issue by justinwoo** [jwiegley/async-pool#14] opened 2019-03-03 15:34 UTC
Version 0.9.0.2 on Hackage requires base < 4.12, which leads to that this package is broken on Nix: https://hydra.nixos.org/build/86369536/nixlog/1

Could you release a newer version sometime?

**Comment by masaeedu** [comment] 2019-05-27 19:46
I think this might be fixed now. See https://github.com/haskell-infra/hackage-trustees/issues/229

**Comment by vdukhovni** [comment] 2019-11-17 00:31
It has been quite some time since 0.9.0.2. I'd like to second the call for a fresh release.

But I would also like to see this package in stackage (https://github.com/commercialhaskell/stackage/blob/master/README.md).

**Closed** 2019-11-18 08:41 UTC

**Comment by vdukhovni** [comment] 2019-11-18 09:14
The issue is closed, without comment. Does that mean a post-0.9.0.2 release is planned, or is not yet needed, or not yet ready? There seem to be multiple queued-up post-0.9.0.2 commits in the master branch...

**Comment by justinwoo** [comment] 2019-11-18 09:47
I do not own the project and I am not affiliated in any way

**Comment by vdukhovni** [comment] 2019-11-18 09:51
> I do not own the project and I am not affiliated in any way

Understood. I opened a new issue instead of continuing to update yours.
